### ISSUE TITLE
LST divided by 100

### ISSUE THREAD

**Issue by jvaldiviesob** [AliciaPython/GSSM1km#2]
Hello! I hope you're well. I have a question: Why do you divide the LST by 100 on lines 310 and 311? I was reviewing the training values ​​and they are in C°, while when divided by 100 they remain in C°/100 (since in the LST scripts the data is already corrected by scale and transformed from Kelvin to Celsius correctly). Thanks in advance!

**Comment by QianqianHan96** [comment]
Hello, 

which LST scripts you are referring to if I may ask?

I used https://github.com/shilosh/ContinuousLST but I reorganized his scripts. So when I export the processed LST, I multiplied 100 to convert float to int to save storage space. See line 171 in https://code.earthengine.google.com/4f372d709c61c48eb5082775f03d2018

Hope this solved your doubt.

**Comment by jvaldiviesob** [comment]
Thank you very much, in my case I used the script directly (without reorganizing) and for my region it is not necessary to divide by 100 in the main. Thank you very much, question resolved.
